[package]
name = "attempt-this-online"
version = "0.1.16"
edition = "2021"
default-run = "attempt-this-online"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.*"
tokio = { version = "1.*", features = ["full"] }
futures-util = "0.3.*"
rmp = "0.8.*"
serde = { version = "1.0.*", features = ["derive"] }
rmp-serde = "1.1.*"
